// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGEa2B4oe8dF50lhoh9Vcr7erLsTiasRA',
    appId: '1:1005034944517:web:c34f8e630e5cea56c0846c',
    messagingSenderId: '1005034944517',
    projectId: 'signal-11f89',
    authDomain: 'signal-11f89.firebaseapp.com',
    storageBucket: 'signal-11f89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe9BzJELtYrLqYmIhe3W32LZVvCJLw5Q4',
    appId: '1:1005034944517:android:a11479b629dbba54c0846c',
    messagingSenderId: '1005034944517',
    projectId: 'signal-11f89',
    storageBucket: 'signal-11f89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEz0ojPXETHVU9ZxJVPA8UmuAWpg7a4Wk',
    appId: '1:1005034944517:ios:ccf9d54cdd2780c8c0846c',
    messagingSenderId: '1005034944517',
    projectId: 'signal-11f89',
    storageBucket: 'signal-11f89.appspot.com',
    iosBundleId: 'com.example.signal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEz0ojPXETHVU9ZxJVPA8UmuAWpg7a4Wk',
    appId: '1:1005034944517:ios:ccf9d54cdd2780c8c0846c',
    messagingSenderId: '1005034944517',
    projectId: 'signal-11f89',
    storageBucket: 'signal-11f89.appspot.com',
    iosBundleId: 'com.example.signal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGEa2B4oe8dF50lhoh9Vcr7erLsTiasRA',
    appId: '1:1005034944517:web:2c663771de04a3b7c0846c',
    messagingSenderId: '1005034944517',
    projectId: 'signal-11f89',
    authDomain: 'signal-11f89.firebaseapp.com',
    storageBucket: 'signal-11f89.appspot.com',
  );
}
